# Generated by Django 4.1 on 2022-08-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('movieTitle', models.CharField(max_length=255)),
                ('movieDescription', models.CharField(max_length=255)),
                ('movieGenre', models.CharField(default='Action', max_length=255)),
            ],
        ),
    ]
